# Generated by Django 6.0.5 on 2026-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='additional_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='specific_area',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AddField(
            model_name='customer',
            name='subcity',
            field=models.CharField(choices=[('BL', 'Bole'), ('YK', 'Yeka'), ('LM', 'Lemi Kura'), ('AR', 'Arada'), ('AD', 'Addis Ketema'), ('LF', 'Nifas Silk Lafto'), ('AK', 'Akaky Kality'), ('KR', 'Kirkos'), ('GL', 'Gullele'), ('LD', 'Lideta'), ('KF', 'Kolfe Keranio')], default='BL', max_length=100),
            preserve_default=False,
        ),
    ]
